# Generated by Django 5.2.11 on 2026-07-14 11:52

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('commercial', 'Commercial')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('step', models.CharField(blank=True, null=True)),
                ('type', models.CharField(choices=[('navigation', 'Navigation'), ('url', 'URL'), ('erreur', 'Erreur')], max_length=20)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'help_document',
            },
        ),
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.PROTECT, to='authentification.adminuser')),
            ],
            options={
                'db_table': 'admin_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('commercial', models.ForeignKey(db_column='commercial_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commercial_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
