# Generated by Django 5.2.11 on 2026-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(db_column='first_name', default='Ny Aina', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(db_column='last_name', default='Ny Aina', max_length=100),
            preserve_default=False,
        ),
    ]
