# Generated by Django 5.2.11 on 2026-04-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
