# Generated by Django 5.2.11 on 2026-04-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(db_column='email', default='taf.rand37@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
