# Generated by Django 5.2.11 on 2026-04-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('website_url', models.TextField(unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('is_company', models.BooleanField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.TextField(unique=True)),
                ('purchase_unit_price', models.FloatField()),
                ('sale_unit_price', models.FloatField()),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_proposal', models.DateField()),
                ('amount_ht', models.FloatField()),
                ('amount_ttc', models.FloatField()),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, to='commercial.client')),
                ('commercial', models.ForeignKey(db_column='commercial_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commercial_proposal',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('tax_identification_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField()),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='commercial.client')),
                ('company_type', models.ForeignKey(db_column='company_type_id', on_delete=django.db.models.deletion.PROTECT, to='commercial.companytype')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('id_card_number', models.CharField(max_length=20, unique=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='commercial.client')),
            ],
            options={
                'db_table': 'individual',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='commercial.category')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='commercial.product')),
            ],
            options={
                'db_table': 'product_category',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='commercial.ProductCategory', to='commercial.category'),
        ),
        migrations.CreateModel(
            name='ProposalProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coefficient', models.FloatField()),
                ('quantity', models.FloatField()),
                ('purchase_unit_price', models.FloatField()),
                ('sale_unit_price', models.FloatField()),
                ('commercial_proposal', models.ForeignKey(db_column='commercial_proposal_id', on_delete=django.db.models.deletion.PROTECT, related_name='proposal_products', to='commercial.commercialproposal')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.product')),
            ],
            options={
                'db_table': 'proposal_product',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, to='commercial.unit'),
        ),
    ]
