# Generated by Django 5.2.11 on 2026-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
