# Generated by Django 5.2.11 on 2026-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_commercialproposal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='validity_period',
            field=models.IntegerField(default=30),
        ),
    ]
