# Generated by Django 5.2.11 on 2026-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_remove_commercialproposal_validity_period_and_add_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproduct',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
